{
 "title": "Teamspeak",
 "description": "Sample dashboard for GitHub project https://github.com/TilmannF/teamspeak-prometheus",
 "tags": [
  "prometheus",
  "teamspeak"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(teamspeak_virtualserver_uptime, job)"
   },
   {
    "name": "instance",
    "label": "Instance:",
    "query": "label_values(teamspeak_virtualserver_uptime{job=\"$job\"}, instance)"
   },
   {
    "name": "virtualserver",
    "label": "Virtual Server:",
    "query": "label_values(teamspeak_virtualserver_uptime{instance=\"$instance\",job=\"$job\"}, virtualserver_name)"
   },
   {
    "name": "maxclients",
    "query": "query_result(teamspeak_virtualserver_maxclients{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"})"
   }
  ]
 },
 "panels": [
  {
   "title": "Online Client",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(teamspeak_player_online) by (clid, cid, client_nickname, connection_client_ip, client_version, client_away, client_away_message, client_input_muted, client_output_muted, client_lastconnected, client_country)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "stat",
   "description": "teamspeak_virtualserver_clientsonline - teamspeak_virtualserver_queryclientsonline",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "teamspeak_virtualserver_clientsonline{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"} - teamspeak_virtualserver_queryclientsonline{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}"
    }
   ]
  },
  {
   "title": "Max clients",
   "type": "stat",
   "description": "Based on teamspeak_virtualserver_maxclients",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "teamspeak_virtualserver_maxclients{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}"
    }
   ]
  },
  {
   "title": "Reserved slots",
   "type": "stat",
   "description": "teamspeak_virtualserver_reserved_slots",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "teamspeak_virtualserver_reserved_slots{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}"
    }
   ]
  },
  {
   "title": "Channels online",
   "type": "stat",
   "description": "Based on teamspeak_virtualserver_channelsonline",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "teamspeak_virtualserver_channelsonline{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "teamspeak_virtualserver_uptime",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "teamspeak_virtualserver_uptime{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}"
    }
   ]
  },
  {
   "title": "Connected clients",
   "type": "timeseries",
   "description": "Based on teamspeak_virtualserver_clientsonline & teamspeak_virtualserver_queryclientsonline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "teamspeak_virtualserver_clientsonline{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"} - teamspeak_virtualserver_queryclientsonline{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}",
     "legendFormat": "Connected clients"
    }
   ]
  },
  {
   "title": "Packet loss",
   "type": "timeseries",
   "description": "Based on teamspeak_virtualserver_total_packetloss_total, teamspeak_virtualserver_total_packetloss_speech, teamspeak_virtualserver_total_packetloss_keepalive, teamspeak_virtualserver_total_packetloss_control",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "teamspeak_virtualserver_total_packetloss_total{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "teamspeak_virtualserver_total_packetloss_speech{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}",
     "legendFormat": "Speech"
    },
    {
     "expr": "teamspeak_virtualserver_total_packetloss_keepalive{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}",
     "legendFormat": "Keepalive"
    },
    {
     "expr": "teamspeak_virtualserver_total_packetloss_control{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}",
     "legendFormat": "Control"
    }
   ]
  },
  {
   "title": "Average ping",
   "type": "timeseries",
   "description": "Based on teamspeak_virtualserver_total_ping",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "teamspeak_virtualserver_total_ping{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"} ",
     "legendFormat": "Ping"
    }
   ]
  },
  {
   "title": "Packets",
   "type": "timeseries",
   "description": "Based on teamspeak_connection_packets_received_total, teamspeak_connection_packets_received_speech, teamspeak_connection_packets_received_keepalive, teamspeak_connection_packets_received_control, teamspeak_connection_packets_sent_total, teamspeak_connection_packets_sent_speech, teamspeak_connection_packets_sent_keepalive & teamspeak_connection_packets_sent_control",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(teamspeak_connection_packets_received_total{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Incoming total"
    },
    {
     "expr": "irate(teamspeak_connection_packets_received_speech{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Incoming speech"
    },
    {
     "expr": "irate(teamspeak_connection_packets_received_keepalive{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Incoming keepalive"
    },
    {
     "expr": "irate(teamspeak_connection_packets_received_control{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Incoming control"
    },
    {
     "expr": "-irate(teamspeak_connection_packets_sent_total{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Outgoing total"
    },
    {
     "expr": "-irate(teamspeak_connection_packets_sent_speech{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Outgoing speech"
    },
    {
     "expr": "-irate(teamspeak_connection_packets_sent_keepalive{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Outgoing keepalive"
    },
    {
     "expr": "-irate(teamspeak_connection_packets_sent_control{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Outgoing control"
    }
   ]
  },
  {
   "title": "Bandwith last second",
   "type": "timeseries",
   "description": "Based on teamspeak_connection_bandwidth_received_last_second_total & teamspeak_connection_bandwidth_sent_last_second_total ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "teamspeak_connection_bandwidth_received_last_second_total{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"} * 8",
     "legendFormat": "Incoming"
    },
    {
     "expr": "-teamspeak_connection_bandwidth_sent_last_second_total{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"} * 8",
     "legendFormat": "Outgoing"
    }
   ]
  },
  {
   "title": "Bandwidth last minute",
   "type": "timeseries",
   "description": "Based on teamspeak_connection_bandwidth_received_last_minute_total &  teamspeak_connection_bandwidth_sent_last_minute_total",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "teamspeak_connection_bandwidth_received_last_minute_total{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"} * 8",
     "legendFormat": "Incoming"
    },
    {
     "expr": "-teamspeak_connection_bandwidth_sent_last_minute_total{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"} * 8",
     "legendFormat": "Outgoing"
    }
   ]
  },
  {
   "title": "Connection bytes",
   "type": "timeseries",
   "description": "Based on teamspeak_connection_bytes_received_total, teamspeak_connection_bytes_received_speech, teamspeak_connection_bytes_received_keepalive, teamspeak_connection_bytes_received_control, teamspeak_connection_bytes_sent_total, teamspeak_connection_bytes_sent_speech, teamspeak_connection_bytes_sent_keepalive, teamspeak_connection_bytes_sent_control",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "irate(teamspeak_connection_bytes_received_total{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Incoming total"
    },
    {
     "expr": "irate(teamspeak_connection_bytes_received_speech{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Incoming speech"
    },
    {
     "expr": "irate(teamspeak_connection_bytes_received_keepalive{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Incoming keepalive"
    },
    {
     "expr": "irate(teamspeak_connection_bytes_received_control{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Incoming control"
    },
    {
     "expr": "-irate(teamspeak_connection_bytes_sent_total{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Outgoing total"
    },
    {
     "expr": "-irate(teamspeak_connection_bytes_sent_speech{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Outgoing speech"
    },
    {
     "expr": "-irate(teamspeak_connection_bytes_sent_keepalive{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Outgoing keepalive"
    },
    {
     "expr": "-irate(teamspeak_connection_bytes_sent_control{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Outgoing control"
    }
   ]
  },
  {
   "title": "Upload / Download",
   "type": "timeseries",
   "description": "Based on teamspeak_virtualserver_total_bytes_uploaded & teamspeak_virtualserver_total_bytes_downloaded",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(teamspeak_virtualserver_total_bytes_uploaded{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}[5m])",
     "legendFormat": "Uploaded"
    },
    {
     "expr": "-irate(teamspeak_virtualserver_total_bytes_downloaded{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}[5m])",
     "legendFormat": "Downloaded"
    }
   ]
  }
 ]
}